### PR TITLE
Add IDS tutorials to package

### PR DESCRIPTION
**Pull request by lee-suddaby**
Current points I've thought of for review:
- Might want to take a look at the descriptions I've written for the tutorials
- URLs for tutorials in `_pkgdown.yml` - Are they valid?
- For tutorial 03, `scales` and `fivethirtyeight` are required packages, as well as the usual ones in all tutorials. As far as I can tell, this one doesn't require the `dsbox` package at all.

### CODE REVIEW

**Comment by mine-cetinkaya-rundel** [comment]
This is looking great @lee-suddaby!

I made a series of minor edits. Currently, the package build is failing here but that's because of a known issue apparently, so you can ignore that.

Two items to do before we merge:

- Can you take a look at the web scraping tutorial to confirm the setup chunks are indeed needed? I couldn't tell where they get used exactly.
- Can you install this package on a fresh RStudio instance and try running each of the tutorials to see if they work, and if not report here any errors you get?

Thanks!

**Comment by lee-suddaby** [comment]
In response to the first point, yes the setup chunks are needed - that's how I did the progressive updating of the datasets during scraping and cleaning.

**Comment by lee-suddaby** [comment]
@mine-cetinkaya-rundel Now (some of) the points from running the tutorials:
- In general, they all take 2-3 minutes just to get started on my machine, which is much longer than it takes to render them to HTML (that takes more like 10 seconds). Don't know if this is a normal time for deployment, so just putting it out there.
- In 01-edibnb, for the question in the "Building a histogram", the graph is produced alright, but submitting the answers throws the following error: "`Uh oh, the R code produced a syntax error: <text>:1:51: unexpected input 1: ggplot(data = edibnb, mapping = aes(x = price)) + ^`". This error doesn't appear on similar exercises, e.g. the following exercise on faceted historgrams.
- 02-accidents: Same as above for the first and second exercises in the "Accident Severity" section. Example error: "`Uh oh, the R code produced a syntax error: <text>:1:80: unexpected input 1: ggplot(data = accidents, aes(x = accident_severity, fill = light_conditions)) + ^`".
- 03-collegemajors: There was a wee problem with exercise setup chunks, meaning that a mutated variable was available before the part of the tutorial in which the student created said variable. I've patched that.
- Similar errors are in the others for the "Top 3 majors for proportion of women" exercise. This seems to come up a lot.

**Comment by lee-suddaby** [comment]
I'll keep working through the tutorials tomorrow.

**Comment by lee-suddaby** [comment]
Actually, Re: That "Uh oh, the R code produced a syntax error", it only seems to happen when I copy and paste the code solution (yes, I'm being lazy sometimes), but it's alright when one just fills in the blanks in the code...

See also: https://community.rstudio.com/t/solution-gives-syntax-error-when-copying-and-pasting-it/76005

Looks like it's coming from `grade_learnr`: https://rdrr.io/github/rstudio-education/gradethis/src/R/grade_learnr.R

Update: found [an issue](https://github.com/rstudio-education/gradethis/issues/135) opened in the gradethis repository, albeit with no comments so far. Further experimenting on my part reveals to difference even in hidden characters between the two that I can discern (using Notepad++ and a hex editor), but I suppose I did use clipboard for copying and pasting in both cases, so I may have missed something.

**Comment by lee-suddaby** [comment]
Points from 05-moneyinpolitics:
- Somehow, the datasets for `pac-all` and `pac-all-raw` had ended up being identical (though they didn't start out that was in csv form!) So I've updated the raw dataset to actually be the raw one.
- For a lot of the exercises, I think really all of the ones using either of the pac_all datasets, learnr returns "`Error occurred while checking the submission`", while the error left in the console is "`Error in parsed_check_code[[length(parsed_check_code)]]: attempt to select less than one element in integerOneIndex`". Note that this doesn't seem to occur with any of the exercises in making the final visualisation with the `pac_all_final` dataframe. I'll try re-installing `dsbox` with the updated dataframes as above and see if that helps at all.

**Comment by lee-suddaby** [comment]
Should have said before, no problems that I found with 04-legosales.

**Comment by lee-suddaby** [comment]
For 06-dcbikeshare, I've made a few necessary changes in the commit above, but there weren't any (unique) problems other than that.

**Comment by lee-suddaby** [comment]
Same for 07-exploregss, just a few small changes to make that I have done. Other than that, it looks good to go to me.

**Comment by lee-suddaby** [comment]
And, finally, nothing to report for 08-bootstrapgss that I haven't just fixed.

The ìnfer` package is now added as an Import in DESCRIPTION, like other packages used in the tutorials, since it is used in the final tutorial for bootstrapping.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!

**Pull request merged**
