### PR TITLE
Adding grade_this and grade_this_code for Airbnb listings tutorial

### PR DESCRIPTION
**Pull request by natashadunstan**

### CODE REVIEW

**Review by mine-cetinkaya-rundel — COMMENTED** [review]
There are some helper functions like `pass_if()` and `pass_if_equal()` (and their `fail_*()` versions) in gradethis. Could those be used here?

**Comment by sasha99edinburgh** [comment]
I am having trouble expressing 'OR' and 'AND' statements using pass_if_equal( )/ fail_if_equal( ). Is there a way to do it? As for pass_if( ) and fail_if( ), I don't think we can use them according to this: [https://github.com/rstudio-education/gradethis/issues/197](url)

**Comment by natashadunstan** [comment]
I am having trouble expressing 'OR' and 'AND' statements using pass_if_equal( )/ fail_if_equal( ). Is there a way to do it? As for pass_if( ) and fail_if( ), I don't think we can use them according to this: https://github.com/rstudio-education/gradethis/issues/197.

**Comment by natashadunstan** [comment]
Both of them work. Which method would you recommend me using?

image

image

**Comment by mine-cetinkaya-rundel** [comment]
I see, the second one, with regular `if()` is better then, it does indeed seem more clear.

**Pull request merged**
